name: MapSwap
version: ${project.version}
main: com.djempie.mapswap.MapSwap
api-version: 1.16
authors: [ Djempie ]
description: A simple plugin to swap adventure maps on-the-fly
commands:
  createGroup:
    description: Create a group to play adventures with.
    aliases:
      - createGroup
      - cg
    permission: adventures.admin
    permission-message: You do not have permission to use this command!
    usage: /createGroup <team name>
  leaveTeam:
    description: Leave current team.
    aliases:
      - leaveTeam
      - let
    permission: adventures.user
    permission-message: You do not have permission to use this command!
    usage: /leaveTeam
  joinTeam:
    description: Join an existing team.
    aliases:
      - joinTeam
      - jt
    permission: adventures.user
    permission-message: You do not have permission to use this command!
    usage: /joinTeam <team name>
  listTeams:
    description: List all teams.
    aliases:
      - listTeams
      - lit
    permission: adventures.user
    permission-message: You do not have permission to use this command!
    usage: /listTeams
  teamInfo:
    description: Get a team's info.
    aliases:
      - teamInfo
      - ti
    permission: adventures.user
    permission-message: You do not have permission to use this command!
    usage: /teamInfo <team name>
  startAdventure:
    description: Start a new adventure.
    aliases:
      - startAdventure
      - saa
    permission: adventures.admin
    permission-message: You do not have permission to use this command!
    usage: /startAdventure <adventure name>
  stopAdventure:
    description: Stop current adventure.
    aliases:
      - stopAdventure
      - soa
    permission: adventures.admin
    permission-message: You do not have permission to use this command!
    usage: /stopAdventure
  listAdventures:
    description: List all adventures.
    aliases:
      - listAdventures
      - la
    permission: adventures.user
    permission-message: You do not have permission to use this command!
    usage: /listAdventures
  adventureInfo:
    description: Get info on a specific adventure.
    aliases:
      - adventureInfo
      - ai
    permission: adventures.user
    permission-message: You do not have permission to use this command!
    usage: /adventureInfo <adventure name>